import type Chunk from '../Chunk';
import ExternalChunk from '../ExternalChunk';
import ExternalModule from '../ExternalModule';
import type Module from '../Module';
import type ChildScope from '../ast/scopes/ChildScope';
import type SyntheticNamedExportVariable from '../ast/variables/SyntheticNamedExportVariable';
import type { Variable } from '../ast/variables/Variable';
import type { GetInterop, InternalModuleFormat } from '@rollup/types';
import type { DependenciesToBeDeconflicted } from '@rollup/types';
export declare function deconflictChunk(modules: readonly Module[], dependenciesToBeDeconflicted: DependenciesToBeDeconflicted, imports: ReadonlySet<Variable>, usedNames: Set<string>, format: InternalModuleFormat, interop: GetInterop, preserveModules: boolean, externalLiveBindings: boolean, chunkByModule: ReadonlyMap<Module, Chunk>, externalChunkByModule: ReadonlyMap<ExternalModule, ExternalChunk>, syntheticExports: ReadonlySet<SyntheticNamedExportVariable>, exportNamesByVariable: ReadonlyMap<Variable, readonly string[]>, accessedGlobalsByScope: ReadonlyMap<ChildScope, ReadonlySet<string>>, includedNamespaces: ReadonlySet<Module>): void;
