import type { AnnotationType } from "../rollup/types";
import type Module from '../Module';
import type { InternalModuleFormat, LogHandler, NormalizedInputOptions, RollupLog } from 'rollup';
export declare function error(base: Error | RollupLog): never;
export declare function getRollupError(base: RollupLog): Error & RollupLog;
export declare function augmentCodeLocation(properties: RollupLog, pos: number | {
    column: number;
    line: number;
}, source: string, id: string): void;
declare const symbolAugmented: unique symbol;
type AugmentedRollupLog = {
    [symbolAugmented]?: boolean;
} & RollupLog;
export declare function augmentLogMessage(log: AugmentedRollupLog): void;
export declare function logAddonNotGenerated(message: string, hook: string, plugin: string): RollupLog;
export declare function logAlreadyClosed(): RollupLog;
export declare function logAmbiguousExternalNamespaces(binding: string, reexportingModule: string, usedModule: string, sources: string[]): RollupLog;
export declare function logAnonymousPluginCache(): RollupLog;
export declare function logAssetNotFinalisedForFileName(name: string): RollupLog;
export declare function logAssetReferenceIdNotFoundForSetSource(assetReferenceId: string): RollupLog;
export declare function logAssetSourceAlreadySet(name: string): RollupLog;
export declare function logNoAssetSourceSet(assetName: string): RollupLog;
export declare function logBadLoader(id: string): RollupLog;
export declare function logCannotCallNamespace(name: string): RollupLog;
export declare function logCannotEmitFromOptionsHook(): RollupLog;
export declare function logChunkNotGeneratedForFileName(name: string): RollupLog;
export declare function logChunkInvalid({ fileName, code }: {
    code: string;
    fileName: string;
}, { pos, message }: {
    pos: number;
    message: string;
}): RollupLog;
export declare function logCircularDependency(cyclePath: string[]): RollupLog;
export declare function logCircularReexport(exportName: string, exporter: string): RollupLog;
export declare function logCyclicCrossChunkReexport(exportName: string, exporter: string, reexporter: string, importer: string, preserveModules: boolean): RollupLog;
export declare function logDeprecation(deprecation: string, urlSnippet: string, plugin?: string): RollupLog;
export declare function logConstVariableReassignError(): {
    code: string;
    message: string;
};
export declare function logDuplicateArgumentNameError(name: string): RollupLog;
export declare function logDuplicateExportError(name: string): RollupLog;
export declare function logDuplicateImportOptions(): RollupLog;
export declare function logDuplicatePluginName(plugin: string): RollupLog;
export declare function logEmptyChunk(chunkName: string): RollupLog;
export declare function logEval(id: string): RollupLog;
export declare function logExternalSyntheticExports(id: string, importer: string): RollupLog;
export declare function logFailAfterWarnings(): RollupLog;
export declare function logFileNameConflict(fileName: string): RollupLog;
export declare function logFileReferenceIdNotFoundForFilename(assetReferenceId: string): RollupLog;
export declare function logFirstSideEffect(source: string, id: string, { line, column }: {
    column: number;
    line: number;
}): RollupLog;
export declare function logIllegalIdentifierAsName(name: string): RollupLog;
export declare function logIllegalImportReassignment(name: string, importingId: string): RollupLog;
export declare function logInconsistentImportAttributes(existingAttributes: Record<string, string>, newAttributes: Record<string, string>, source: string, importer: string): RollupLog;
export declare function logInvalidAnnotation(comment: string, id: string, type: AnnotationType): RollupLog;
export declare function logInputHookInOutputPlugin(pluginName: string, hookName: string): RollupLog;
export declare function logCannotAssignModuleToChunk(moduleId: string, assignToAlias: string, currentAlias: string): RollupLog;
export declare function logCannotBundleConfigAsEsm(originalError: Error): RollupLog;
export declare function logCannotLoadConfigAsCjs(originalError: Error): RollupLog;
export declare function logCannotLoadConfigAsEsm(originalError: Error): RollupLog;
export declare function logInvalidExportOptionValue(optionValue: string): RollupLog;
export declare function logIncompatibleExportOptionValue(optionValue: string, keys: readonly string[], entryModule: string): RollupLog;
export declare function logInternalIdCannotBeExternal(source: string, importer: string): RollupLog;
export declare function logImportOptionsAreInvalid(importer: string): RollupLog;
export declare function logImportAttributeIsInvalid(importer: string): RollupLog;
export declare function logInvalidLogPosition(plugin: string): RollupLog;
export declare function logInvalidOption(option: string, urlSnippet: string, explanation: string, value?: string | boolean | null): RollupLog;
export declare function logInvalidAddonPluginHook(hook: string, plugin: string): RollupLog;
export declare function logInvalidFunctionPluginHook(hook: string, plugin: string): RollupLog;
export declare function logInvalidRollupPhaseForChunkEmission(): RollupLog;
export declare function logInvalidSetAssetSourceCall(): RollupLog;
export declare function logInvalidFormatForTopLevelAwait(id: string, format: InternalModuleFormat): RollupLog;
export declare function logMissingConfig(): RollupLog;
export declare function logMissingEntryExport(binding: string, exporter: string): RollupLog;
export declare function logMissingExport(binding: string, importingModule: string, exporter: string, missingButExportExists: boolean): RollupLog;
export declare function logMissingExternalConfig(file: string): RollupLog;
export declare function logMissingGlobalName(externalId: string, guess: string): RollupLog;
export declare function logImplicitDependantCannotBeExternal(unresolvedId: string, implicitlyLoadedBefore: string): RollupLog;
export declare function logUnresolvedImplicitDependant(unresolvedId: string, implicitlyLoadedBefore: string): RollupLog;
export declare function logImplicitDependantIsNotIncluded(module: Module): RollupLog;
export declare function logMissingJsxExport(name: string, exporter: string, importer: string): RollupLog;
export declare function logMissingNameOptionForIifeExport(): RollupLog;
export declare function logMissingNameOptionForUmdExport(): RollupLog;
export declare function logMissingNodeBuiltins(externalBuiltins: string[]): RollupLog;
export declare function logMissingFileOrDirOption(): RollupLog;
export declare function logMixedExport(facadeModuleId: string, name?: string): RollupLog;
export declare function logModuleLevelDirective(directive: string, id: string): RollupLog;
export declare function logNamespaceConflict(binding: string, reexportingModuleId: string, sources: string[]): RollupLog;
export declare function logNoFileSystemInBrowser(method: string): RollupLog;
export declare function logNoTransformMapOrAstWithoutCode(pluginName: string): RollupLog;
export declare function logOnlyInlineSourcemapsForStdout(): RollupLog;
export declare function logOptimizeChunkStatus(chunks: number, smallChunks: number, pointInTime: string): RollupLog;
export declare function logParseError(message: string, pos?: number): RollupLog;
export declare function logRedeclarationError(name: string): RollupLog;
export declare function logReservedNamespace(namespace: string): RollupLog;
export declare function logModuleParseError(error: Error, moduleId: string): RollupLog;
export declare function logPluginError(error: Omit<RollupLog, 'code'> & {
    code?: unknown;
}, plugin: string, { hook, id }?: {
    hook?: string;
    id?: string;
}): RollupLog;
export declare function logShimmedExport(id: string, binding: string): RollupLog;
export declare function logSourcemapBroken(plugin: string): RollupLog;
export declare function logConflictingSourcemapSources(filename: string): RollupLog;
export declare function logInvalidSourcemapForError(error: Error, id: string, column: number, line: number, pos: number): RollupLog;
export declare function logSyntheticNamedExportsNeedNamespaceExport(id: string, syntheticNamedExportsOption: boolean | string): RollupLog;
export declare function logThisIsUndefined(): RollupLog;
export declare function logUnexpectedNamedImport(id: string, imported: string, isReexport: boolean): RollupLog;
export declare function logUnexpectedNamespaceReexport(id: string): RollupLog;
export declare function logUnknownOption(optionType: string, unknownOptions: string[], validOptions: string[]): RollupLog;
export declare function logEntryCannotBeExternal(unresolvedId: string): RollupLog;
export declare function logExternalModulesCannotBeIncludedInManualChunks(source: string): RollupLog;
export declare function logExternalModulesCannotBeTransformedToModules(source: string): RollupLog;
export declare function logUnresolvedEntry(unresolvedId: string): RollupLog;
export declare function logUnresolvedImport(source: string, importer: string): RollupLog;
export declare function logUnresolvedImportTreatedAsExternal(source: string, importer: string): RollupLog;
export declare function logUnusedExternalImports(externalId: string, names: string[], importers: string[]): RollupLog;
export declare function logFailedValidation(message: string): RollupLog;
export declare function warnDeprecation(deprecation: string, urlSnippet: string, activeDeprecation: boolean, options: NormalizedInputOptions, plugin?: string): void;
export declare function warnDeprecationWithOptions(deprecation: string, urlSnippet: string, activeDeprecation: boolean, log: LogHandler, strictDeprecations: boolean, plugin?: string): void;
export {};
