import type { NormalizedInputOptions, NormalizedOutputOptions, OutputChunk, PreRenderedChunk, RenderedChunk } from '@rollup/types';
import { Bundle as MagicStringBundle, type SourceMap } from 'magic-string';
import type ImportExpression from './ast/nodes/ImportExpression';
import type { Variable } from './ast/variables/Variable';
import ExternalChunk from './ExternalChunk';
import ExternalModule from './ExternalModule';
import Module from './Module';
import type { GenerateCodeSnippets } from "@rollup/types";
import type { HashPlaceholderGenerator } from './utils/hashPlaceholders';
import type { OutputBundleWithPlaceholders } from './utils/outputBundle';
import type { PluginDriver } from './utils/PluginDriver';
export type ModuleDeclarations = {
    dependencies: ChunkDependency[];
    exports: ChunkExports;
};
type PreliminaryFileName = PreliminaryFileNameWithPlaceholder | FixedPreliminaryFileName;
export type ChunkRenderResult = {
    chunk: Chunk;
    magicString: MagicStringBundle;
    preliminaryFileName: PreliminaryFileName;
    preliminarySourcemapFileName: PreliminaryFileName | null;
    usedModules: Module[];
};
type PreliminaryFileNameWithPlaceholder = {
    fileName: string;
    hashPlaceholder: string;
};
type FixedPreliminaryFileName = {
    fileName: string;
    hashPlaceholder: null;
};
export type ResolvedDynamicImport = ({
    chunk: Chunk;
    externalChunk: null;
    facadeChunk: Chunk | undefined;
    resolution: Module;
} | {
    chunk: null;
    externalChunk: ExternalChunk;
    facadeChunk: null;
    resolution: ExternalModule;
} | {
    chunk: null;
    externalChunk: null;
    facadeChunk: null;
    resolution: string | null;
}) & {
    node: ImportExpression;
};
export type ChunkDependency = {
    attributes: string | null;
    defaultVariableName: string | undefined;
    globalName: string | false | undefined;
    importPath: string;
    imports: ImportSpecifier[] | null;
    isChunk: boolean;
    name: string;
    namedExportsMode: boolean;
    namespaceVariableName: string | undefined;
    reexports: ReexportSpecifier[] | null;
};
export type ChunkExports = {
    exported: string;
    expression: string | null;
    hoisted: boolean;
    local: string;
}[];
export type ReexportSpecifier = {
    imported: string;
    needsLiveBinding: boolean;
    reexported: string;
};
export type ImportSpecifier = {
    imported: string;
    local: string;
};
export default class Chunk {
    defaultVariableName?: undefined;
    dependencies: Set<Chunk | ExternalChunk>;
    readonly entryModules: Module[];
    execIndex: number;
    exportMode: 'none' | 'named' | 'default';
    facadeModule: Module | null;
    namespaceVariableName: string;
    suggestedVariableName: string;
    variableName: string;
    private readonly accessedGlobalsByScope;
    private readonly dynamicEntryModules;
    private dynamicName;
    private readonly exportNamesByVariable;
    private readonly exports;
    private readonly exportsByName;
    private fileName;
    private implicitEntryModules;
    private readonly implicitlyLoadedBefore;
    private readonly imports;
    private includedDynamicImports;
    private readonly includedReexportsByModule;
    private readonly isEmpty;
    private name;
    private needsExportsShim;
    private preRenderedChunkInfo;
    private preliminaryFileName;
    private preliminarySourcemapFileName;
    private renderedChunkInfo;
    private renderedDependencies;
    private readonly renderedModules;
    private sortedExportNames;
    private strictFacade;
    /** Modules with 'allow-extension' that should have preserved exports within the chunk */
    private allowExtensionModules;
    private readonly orderedModules;
    private readonly inputOptions;
    private readonly outputOptions;
    private readonly unsetOptions;
    private readonly pluginDriver;
    private readonly modulesById;
    private readonly chunkByModule;
    private readonly externalChunkByModule;
    private readonly facadeChunkByModule;
    private readonly includedNamespaces;
    private readonly manualChunkAlias;
    private readonly getPlaceholder;
    private readonly bundle;
    private readonly inputBase;
    private readonly snippets;
    constructor(orderedModules: readonly Module[], inputOptions: NormalizedInputOptions, outputOptions: NormalizedOutputOptions, unsetOptions: ReadonlySet<string>, pluginDriver: PluginDriver, modulesById: ReadonlyMap<string, Module | ExternalModule>, chunkByModule: Map<Module, Chunk>, externalChunkByModule: ReadonlyMap<ExternalModule, ExternalChunk>, facadeChunkByModule: Map<Module, Chunk>, includedNamespaces: Set<Module>, manualChunkAlias: string | null, getPlaceholder: HashPlaceholderGenerator, bundle: OutputBundleWithPlaceholders, inputBase: string, snippets: GenerateCodeSnippets);
    private static generateFacade;
    canModuleBeFacade(module: Module, exposedVariables: ReadonlySet<Variable>): boolean;
    finalizeChunk(code: string, map: SourceMap | null, sourcemapFileName: string | null, hashesByPlaceholder: Map<string, string>): OutputChunk;
    generateExports(): void;
    generateFacades(): Chunk[];
    private canPreserveModuleExports;
    getChunkName(): string;
    getExportNames(): string[];
    getFileName(): string;
    getImportPath(importer: string): string;
    getPreliminaryFileName(): PreliminaryFileName;
    getPreliminarySourcemapFileName(): PreliminaryFileName | null;
    getRenderedChunkInfo(): RenderedChunk;
    getVariableExportName(variable: Variable): string;
    link(): void;
    inlineTransitiveImports(): void;
    render(): Promise<ChunkRenderResult>;
    private addImplicitlyLoadedBeforeFromModule;
    private addNecessaryImportsForFacades;
    private assignFacadeName;
    private checkCircularDependencyImport;
    private ensureReexportsAreAvailableForModule;
    private generateVariableName;
    private getChunkExportDeclarations;
    private getDependenciesToBeDeconflicted;
    private getDynamicDependencies;
    private getDynamicImportStringAndAttributes;
    private getFallbackChunkName;
    private getImportSpecifiers;
    private getIncludedDynamicImports;
    getPreRenderedChunkInfo(): PreRenderedChunk;
    private getPreserveModulesChunkNameFromModule;
    private getReexportSpecifiers;
    private getReferencedFiles;
    private getRenderedDependencies;
    private inlineChunkDependencies;
    private renderModules;
    private setDynamicImportResolutions;
    private setIdentifierRenderResolutions;
    private setImportMetaResolutions;
    private setUpChunkImportsAndExportsForModule;
}
export {};
