import type { ModuleInfo, ModuleJSON, NormalizedInputOptions, ProgramNode, RollupCache, RollupWatcher } from 'rollup';
import type { ExpressionEntity } from './ast/nodes/shared/Expression';
import GlobalScope from './ast/scopes/GlobalScope';
import { EntityPathTracker } from './ast/utils/PathTracker';
import type ExternalModule from './ExternalModule';
import Module from './Module';
import { ModuleLoader } from './ModuleLoader';
import { BuildPhase } from './utils/buildPhase';
import { PluginDriver } from './utils/PluginDriver';
import type { PureFunctions } from './utils/pureFunctions';
import Queue from './utils/Queue';
export default class Graph {
    private readonly options;
    readonly astLru: import("flru").flruCache<ProgramNode>;
    readonly cachedModules: Map<string, ModuleJSON>;
    readonly deoptimizationTracker: EntityPathTracker;
    entryModules: Module[];
    readonly fileOperationQueue: Queue;
    readonly moduleLoader: ModuleLoader;
    readonly modulesById: Map<string, Module | ExternalModule>;
    needsTreeshakingPass: boolean;
    readonly newlyIncludedVariableInits: Set<ExpressionEntity>;
    phase: typeof BuildPhase.LOAD_AND_PARSE | typeof BuildPhase.ANALYSE | typeof BuildPhase.GENERATE;
    readonly pluginDriver: PluginDriver;
    readonly pureFunctions: PureFunctions;
    readonly scope: GlobalScope;
    readonly watchFiles: Record<string, true>;
    watchMode: boolean;
    private readonly externalModules;
    private implicitEntryModules;
    private modules;
    private pluginCache?;
    constructor(options: NormalizedInputOptions, watcher: RollupWatcher | null);
    build(): Promise<void>;
    getCache(): RollupCache;
    getModuleInfo: (moduleId: string) => ModuleInfo | null;
    private generateModuleGraph;
    private includeStatements;
    private sortModules;
    private warnForMissingExports;
}
