import type { AstNode, CustomPluginOptions, DecodedSourceMapOrMissing, EmittedFile, ExistingDecodedSourceMap, LogLevel, ModuleInfo, ModuleJSON, ModuleOptions, NormalizedInputOptions, PartialNull, PreserveEntrySignaturesOption, ResolvedIdMap, RollupError, RollupLog, TransformModuleJSON } from '@rollup/types';
import MagicString from 'magic-string';
import type { InclusionContext } from '@rollup/types';
import ExportAllDeclaration from './ast/nodes/ExportAllDeclaration';
import ExportDefaultDeclaration from './ast/nodes/ExportDefaultDeclaration';
import type ExportNamedDeclaration from './ast/nodes/ExportNamedDeclaration';
import type ImportDeclaration from './ast/nodes/ImportDeclaration';
import type ImportExpression from './ast/nodes/ImportExpression';
import type MetaProperty from './ast/nodes/MetaProperty';
import type { ExpressionEntity } from './ast/nodes/shared/Expression';
import type { NodeBase } from './ast/nodes/shared/Node';
import ModuleScope from './ast/scopes/ModuleScope';
import type { ObjectPath } from './ast/utils/PathTracker';
import { type EntityPathTracker } from './ast/utils/PathTracker';
import NamespaceVariable from './ast/variables/NamespaceVariable';
import type { Variable } from './ast/variables/Variable';
import ExternalModule from './ExternalModule';
import type Graph from './Graph';
import type { PureFunctions } from './utils/pureFunctions';
import type { RenderOptions } from '@rollup/types';
type ImportDescription = {
    module: Module | ExternalModule;
    name: string;
    source: string;
    start: number;
};
export type AstContext = {
    addDynamicImport: (node: ImportExpression) => void;
    addExport: (node: ExportAllDeclaration | ExportNamedDeclaration | ExportDefaultDeclaration) => void;
    addImport: (node: ImportDeclaration) => void;
    addImportMeta: (node: MetaProperty) => void;
    addImportSource: (importSource: string) => void;
    code: string;
    deoptimizationTracker: EntityPathTracker;
    error: (properties: RollupLog, pos: number) => never;
    fileName: string;
    getExports: () => string[];
    getImportedJsxFactoryVariable: (baseName: string, pos: number, importSource: string) => Variable;
    getModuleExecIndex: () => number;
    getModuleName: () => string;
    getNodeConstructor: (name: string) => typeof NodeBase;
    getReexports: () => string[];
    importDescriptions: Map<string, ImportDescription>;
    includeAllExports: () => void;
    includeDynamicImport: (node: ImportExpression) => void;
    includeVariableInModule: (variable: Variable, path: ObjectPath, context: InclusionContext) => void;
    log: (level: LogLevel, properties: RollupLog, pos: number) => void;
    magicString: MagicString;
    manualPureFunctions: PureFunctions;
    module: Module;
    moduleContext: string;
    newlyIncludedVariableInits: Set<ExpressionEntity>;
    options: NormalizedInputOptions;
    requestTreeshakingPass: () => void;
    traceExport: (name: string) => [variable: Variable | null, options?: VariableOptions];
    traceVariable: (name: string) => Variable | null;
    usesTopLevelAwait: boolean;
};
export type DynamicImport = {
    argument: string | AstNode;
    id: string | null;
    node: ImportExpression;
    resolution: Module | ExternalModule | string | null;
};
export default class Module {
    readonly alternativeReexportModules: Map<Variable, Module>;
    readonly chunkFileNames: Set<string>;
    chunkNames: {
        isUserDefined: boolean;
        name: string;
        priority: number;
    }[];
    readonly cycles: Set<symbol>;
    readonly dependencies: Set<Module | ExternalModule>;
    readonly dynamicDependencies: Set<Module | ExternalModule>;
    readonly dynamicImporters: string[];
    readonly dynamicImports: DynamicImport[];
    excludeFromSourcemap: boolean;
    execIndex: number;
    hasTreeShakingPassStarted: boolean;
    readonly implicitlyLoadedAfter: Set<Module>;
    readonly implicitlyLoadedBefore: Set<Module>;
    readonly importDescriptions: Map<string, ImportDescription>;
    readonly importMetas: MetaProperty[];
    importedFromNotTreeshaken: boolean;
    shebang: undefined | string;
    readonly importers: string[];
    readonly includedDynamicImporters: Module[];
    readonly includedDirectTopLevelAwaitingDynamicImporters: Set<Module>;
    readonly includedImports: Set<Variable>;
    readonly info: ModuleInfo;
    isExecuted: boolean;
    isUserDefinedEntryPoint: boolean;
    magicString: MagicString;
    namespace: NamespaceVariable;
    needsExportShim: boolean;
    originalCode: string;
    originalSourcemap: ExistingDecodedSourceMap | null;
    preserveSignature: PreserveEntrySignaturesOption;
    resolvedIds: ResolvedIdMap;
    scope: ModuleScope;
    readonly sideEffectDependenciesByVariable: Map<Variable, Set<Module>>;
    sourcemapChain: DecodedSourceMapOrMissing[];
    readonly sourcesWithAttributes: Map<string, Record<string, string>>;
    transformFiles?: EmittedFile[];
    private allExportNames;
    private allExportsIncluded;
    private ast;
    private astContext;
    private readonly context;
    private customTransformCache;
    private readonly exportAllModules;
    private readonly exportAllSources;
    private exportNamesByVariable;
    private readonly exportShimVariable;
    private readonly exports;
    private readonly namespaceReexportsByName;
    private readonly reexportDescriptions;
    private relevantDependencies;
    private readonly syntheticExports;
    private syntheticNamespace;
    private transformDependencies;
    private transitiveReexports;
    private readonly graph;
    readonly id: string;
    private readonly options;
    private isEntry;
    private moduleSideEffects;
    private syntheticNamedExports;
    private meta;
    private attributes;
    constructor(graph: Graph, id: string, options: NormalizedInputOptions, isEntry: boolean, moduleSideEffects: boolean | 'no-treeshake', syntheticNamedExports: boolean | string, meta: CustomPluginOptions, attributes: Record<string, string>);
    basename(): string;
    bindReferences(): void;
    cacheInfoGetters(): void;
    error(properties: RollupError, pos: number | undefined): never;
    estimateSize(): number;
    getAllExportNames(): Set<string>;
    getDependenciesToBeIncluded(): Set<Module | ExternalModule>;
    getExportNamesByVariable(): Map<Variable, string[]>;
    getExports(): string[];
    getReexports(): string[];
    getRenderedExports(): {
        removedExports: string[];
        renderedExports: string[];
    };
    getSyntheticNamespace(): Variable;
    getVariableForExportName(name: string, { importerForSideEffects, isExportAllSearch, onlyExplicit, searchedNamesAndModules }?: {
        importerForSideEffects?: Module;
        isExportAllSearch?: boolean;
        onlyExplicit?: boolean;
        searchedNamesAndModules?: Map<string, Set<Module | ExternalModule>>;
    }): [variable: Variable | null, options?: VariableOptions];
    hasEffects(): boolean;
    include(): void;
    includeAllExports(includeNamespaceMembers: boolean): void;
    includeAllInBundle(): void;
    includeExportsByNames(names: readonly string[]): void;
    isIncluded(): boolean | null;
    linkImports(): void;
    log(level: LogLevel, properties: RollupLog, pos: number): void;
    render(options: RenderOptions): {
        source: MagicString;
        usesTopLevelAwait: boolean;
    };
    setSource({ ast, code, customTransformCache, originalCode, originalSourcemap, resolvedIds, sourcemapChain, transformDependencies, transformFiles, ...moduleOptions }: TransformModuleJSON & {
        resolvedIds?: ResolvedIdMap;
        transformFiles?: EmittedFile[] | undefined;
    }): Promise<void>;
    toJSON(): ModuleJSON;
    traceVariable(name: string, { importerForSideEffects, isExportAllSearch, searchedNamesAndModules }?: {
        importerForSideEffects?: Module;
        isExportAllSearch?: boolean;
        searchedNamesAndModules?: Map<string, Set<Module | ExternalModule>>;
    }): Variable | null;
    updateOptions({ meta, moduleSideEffects, syntheticNamedExports }: Partial<PartialNull<ModuleOptions>>): void;
    private addDynamicImport;
    private assertUniqueExportName;
    private addExport;
    private addImport;
    private addImportSource;
    private addImportMeta;
    private addLocationToLogProps;
    private addModulesToImportDescriptions;
    private addRelevantSideEffectDependencies;
    private addSource;
    private getImportedJsxFactoryVariable;
    private getVariableFromNamespaceReexports;
    private includeAndGetAdditionalMergedNamespaces;
    private includeDynamicImport;
    private includeVariable;
    private includeVariableInModule;
    private shimMissingExport;
    private tryParse;
}
type VariableOptions = {
    indirectExternal?: boolean;
    missingButExportExists?: boolean;
};
export {};
