import type MagicString from 'magic-string';
import type { NodeRenderOptions, RenderOptions } from '../../utils/renderHelpers';
import type { DeoptimizableEntity } from '../DeoptimizableEntity';
import type { HasEffectsContext, InclusionContext } from '../ExecutionContext';
import type { NodeInteraction, NodeInteractionAssigned, NodeInteractionCalled } from '../NodeInteractions';
import { type EntityPathTracker, type ObjectPath, type ObjectPathKey } from '../utils/PathTracker';
import type Variable from '../variables/Variable';
import type * as NodeType from './NodeType';
import type PrivateIdentifier from './PrivateIdentifier';
import { type ExpressionEntity, type LiteralValueOrUnknown } from './shared/Expression';
import type { ChainElement, ExpressionNode, IncludeChildren, SkippedChain } from './shared/Node';
import { NodeBase } from './shared/Node';
import type { PatternNode } from './shared/Pattern';
import type Super from './Super';
export default class MemberExpression extends NodeBase implements DeoptimizableEntity, ChainElement, PatternNode {
    object: ExpressionNode | Super;
    property: ExpressionNode | PrivateIdentifier;
    propertyKey: ObjectPathKey;
    type: NodeType.tMemberExpression;
    variable: Variable | null;
    protected assignmentInteraction: NodeInteractionAssigned;
    private accessInteraction;
    private expressionsToBeDeoptimized;
    private dynamicPropertyKey;
    get computed(): boolean;
    set computed(value: boolean);
    get optional(): boolean;
    set optional(value: boolean);
    private get assignmentDeoptimized();
    private set assignmentDeoptimized(value);
    private get bound();
    private set bound(value);
    private get isUndefined();
    private set isUndefined(value);
    bind(): void;
    deoptimizeArgumentsOnInteractionAtPath(interaction: NodeInteraction, path: ObjectPath, recursionTracker: EntityPathTracker): void;
    deoptimizeAssignment(destructuredInitPath: ObjectPath, init: ExpressionEntity): void;
    deoptimizeCache(): void;
    deoptimizePath(path: ObjectPath): void;
    getLiteralValueAtPath(path: ObjectPath, recursionTracker: EntityPathTracker, origin: DeoptimizableEntity): LiteralValueOrUnknown;
    getLiteralValueAtPathAsChainElement(path: ObjectPath, recursionTracker: EntityPathTracker, origin: DeoptimizableEntity): LiteralValueOrUnknown | SkippedChain;
    getReturnExpressionWhenCalledAtPath(path: ObjectPath, interaction: NodeInteractionCalled, recursionTracker: EntityPathTracker, origin: DeoptimizableEntity): [expression: ExpressionEntity, isPure: boolean];
    hasEffects(context: HasEffectsContext): boolean;
    hasEffectsAsChainElement(context: HasEffectsContext): boolean | SkippedChain;
    hasEffectsAsAssignmentTarget(context: HasEffectsContext, checkAccess: boolean): boolean;
    hasEffectsOnInteractionAtPath(path: ObjectPath, interaction: NodeInteraction, context: HasEffectsContext): boolean;
    hasEffectsWhenDestructuring(context: HasEffectsContext, destructuredInitPath: ObjectPath, init: ExpressionEntity): boolean;
    include(context: InclusionContext, includeChildrenRecursively: IncludeChildren): void;
    includeNode(context: InclusionContext): void;
    includeNodeAsAssignmentTarget(context: InclusionContext): void;
    includePath(path: ObjectPath, context: InclusionContext): void;
    includeAsAssignmentTarget(context: InclusionContext, includeChildrenRecursively: IncludeChildren, deoptimizeAccess: boolean): void;
    includeCallArguments(interaction: NodeInteractionCalled, context: InclusionContext): void;
    includeDestructuredIfNecessary(context: InclusionContext, destructuredInitPath: ObjectPath, init: ExpressionEntity): boolean;
    initialise(): void;
    render(code: MagicString, options: RenderOptions, { renderedParentType, isCalleeOfRenderedParent, renderedSurroundingElement }?: NodeRenderOptions): void;
    setAssignedValue(value: ExpressionEntity): void;
    applyDeoptimizations(): void;
    private applyAssignmentDeoptimization;
    private disallowNamespaceReassignment;
    private getDynamicPropertyKey;
    private hasAccessEffect;
}
