import type ArrowFunctionExpression from '../nodes/ArrowFunctionExpression';
import type AwaitExpression from '../nodes/AwaitExpression';
import type CallExpression from '../nodes/CallExpression';
import type FunctionExpression from '../nodes/FunctionExpression';
import type Identifier from '../nodes/Identifier';
import type ImportExpression from '../nodes/ImportExpression';
import type MemberExpression from '../nodes/MemberExpression';
import type ObjectExpression from '../nodes/ObjectExpression';
import type Property from '../nodes/Property';
import type { ExpressionEntity } from '../nodes/shared/Expression';
import type { ExpressionNode } from '../nodes/shared/Node';
export declare function isObjectExpressionNode(node: ExpressionEntity): node is ObjectExpression;
export declare function isPropertyNode(node: unknown): node is Property;
export declare function isArrowFunctionExpressionNode(node: unknown): node is ArrowFunctionExpression;
export declare function isFunctionExpressionNode(node: unknown): node is FunctionExpression;
export declare function isCallExpressionNode(node: unknown): node is CallExpression;
export declare function isMemberExpressionNode(node: ExpressionNode): node is MemberExpression;
export declare function isImportExpressionNode(node: unknown): node is ImportExpression;
export declare function isAwaitExpressionNode(node: unknown): node is AwaitExpression;
export declare function isIdentifierNode(node: unknown): node is Identifier;
