export declare function isFlagSet(flags: number, flag: number): boolean;
export declare function setFlag(flags: number, flag: number, value: boolean): number;
export declare const Flag: {
    readonly included: number;
    readonly deoptimized: number;
    readonly tdzAccessDefined: number;
    readonly tdzAccess: number;
    readonly assignmentDeoptimized: number;
    readonly bound: number;
    readonly isUndefined: number;
    readonly optional: number;
    readonly async: number;
    readonly deoptimizedReturn: number;
    readonly computed: number;
    readonly hasLostTrack: number;
    readonly hasUnknownDeoptimizedInteger: number;
    readonly hasUnknownDeoptimizedProperty: number;
    readonly directlyIncluded: number;
    readonly deoptimizeBody: number;
    readonly isBranchResolutionAnalysed: number;
    readonly await: number;
    readonly method: number;
    readonly shorthand: number;
    readonly tail: number;
    readonly prefix: number;
    readonly generator: number;
    readonly expression: number;
    readonly destructuringDeoptimized: number;
    readonly hasDeoptimizedCache: number;
    readonly hasEffects: number;
    readonly withinTopLevelAwait: number;
    readonly checkedForWarnings: number;
};
